version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:8080"   # Accedes en http://localhost:5000
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=EvaluacionDB;User=sa;Password=SqlServer2025!;TrustServerCertificate=True;
    networks:
      - app_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    ports:
      - "1500:1433"
    environment:
      SA_PASSWORD: "SqlServer2025!"
      ACCEPT_EULA: "Y"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
